### ISSUE TITLE
How can I help and take part in your project?

### ISSUE THREAD

**Issue by DmitryAleksandrovich** [spencer-hanson/GeneticMaze#2]
Hello! I'd like to join your project.
A little about yourself: I'm junior C++ developer, and I don't have commercial development experience. If you have tasks (junior), I'm happy to help project. Sorry with my not very confident English:)

**Comment by spencer-hanson** [comment]
Hello! No problem! I'd actually like to implement some features to the MazeGen part of my code, I was thinking different types of generation algorithms, see <a href="https://en.wikipedia.org/wiki/Maze_generation_algorithm">Here</a> I've currently only implemented a depth-first search algorithm and I am interested in the other types as well, such as Recursive backtrack, Kruskal's algorithm, and Prim's algorithm. And then being able to choose which algorithm to use whenever you run the MazeGen program. Let me know if you have any questions, and feel free to send a pull request if you'd like me to take a look at what you've gotten done!
